import {
  StudentProfile,
  CompanyProfile,
  Internship,
  Swipe,
  Match,
  Application,
  Message,
  Notification,
  ReportItem,
} from '../src/types';

export const SEED_COMPANIES: CompanyProfile[] = [
  {
    id: 'comp-1',
    userId: 'user-comp-1',
    companyName: 'Google India',
    logo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=150&auto=format&fit=crop&q=80',
    description: 'Organizing the world’s information and making it universally accessible and useful.',
    industry: 'Technology / AI & Cloud',
    website: 'https://google.com',
    location: 'Bengaluru & Hyderabad (Hybrid/Remote)',
    companySize: '10,000+ employees',
    foundedYear: 1998,
    socialLinks: { linkedin: 'https://linkedin.com/company/google', github: 'https://github.com/google' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'comp-2',
    userId: 'user-comp-2',
    companyName: 'Swiggy',
    logo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=150&auto=format&fit=crop&q=80',
    description: 'India’s leading on-demand convenience platform delivering food, grocery, and dining experiences.',
    industry: 'E-commerce & Logistics',
    website: 'https://swiggy.com',
    location: 'Bengaluru, India (Remote Available)',
    companySize: '5,000+ employees',
    foundedYear: 2014,
    socialLinks: { linkedin: 'https://linkedin.com/company/swiggy', github: 'https://github.com/swiggy' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'comp-3',
    userId: 'user-comp-3',
    companyName: 'Razorpay',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150&auto=format&fit=crop&q=80',
    description: 'Building the financial infrastructure for modern digital commerce in India and Southeast Asia.',
    industry: 'FinTech / Payments',
    website: 'https://razorpay.com',
    location: 'Bengaluru, India (Remote)',
    companySize: '3,000+ employees',
    foundedYear: 2014,
    socialLinks: { linkedin: 'https://linkedin.com/company/razorpay', github: 'https://github.com/razorpay' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'comp-4',
    userId: 'user-comp-4',
    companyName: 'CRED',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    description: 'A members-only club that rewards individuals for their financial trustworthiness.',
    industry: 'FinTech & Lifestyle',
    website: 'https://cred.club',
    location: 'Bengaluru, India (Hybrid)',
    companySize: '1,000+ employees',
    foundedYear: 2018,
    socialLinks: { linkedin: 'https://linkedin.com/company/cred-club' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'comp-5',
    userId: 'user-comp-5',
    companyName: 'Zerodha Tech',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=150&auto=format&fit=crop&q=80',
    description: 'India’s largest stockbroker, known for open-source software, high-throughput engines, and lean engineering.',
    industry: 'FinTech / Trading Systems',
    website: 'https://zerodha.tech',
    location: 'Bengaluru, India (Remote-First)',
    companySize: '1,200 employees',
    foundedYear: 2010,
    socialLinks: { github: 'https://github.com/zerodha' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'comp-6',
    userId: 'user-comp-6',
    companyName: 'Postman',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=150&auto=format&fit=crop&q=80',
    description: 'The world’s leading API platform used by 30+ million developers across the globe.',
    industry: 'Developer Tools & SaaS',
    website: 'https://postman.com',
    location: 'Bengaluru & San Francisco (Remote)',
    companySize: '1,500+ employees',
    foundedYear: 2014,
    socialLinks: { linkedin: 'https://linkedin.com/company/postman-platform', github: 'https://github.com/postmanlabs' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
  {
    id: 'comp-7',
    userId: 'user-comp-7',
    companyName: 'Atlassian',
    logo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    description: 'Empowering teams worldwide to collaborate, build software, and organize work seamlessly.',
    industry: 'Enterprise Software / Collaboration',
    website: 'https://atlassian.com',
    location: 'Bengaluru, India (Remote Team Anywhere)',
    companySize: '10,000+ employees',
    foundedYear: 2002,
    socialLinks: { linkedin: 'https://linkedin.com/company/atlassian' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-25T10:00:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
  },
  {
    id: 'comp-8',
    userId: 'user-comp-8',
    companyName: 'Flipkart',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    description: 'India’s homegrown e-commerce marketplace driving innovation in supply chain, mobile tech, and AI.',
    industry: 'E-commerce & Retail Tech',
    website: 'https://flipkart.com',
    location: 'Bengaluru, India (Hybrid)',
    companySize: '15,000+ employees',
    foundedYear: 2007,
    socialLinks: { linkedin: 'https://linkedin.com/company/flipkart' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-28T10:00:00Z',
    updatedAt: '2026-01-28T10:00:00Z',
  },
  {
    id: 'comp-9',
    userId: 'user-comp-9',
    companyName: 'InMobi',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=150&auto=format&fit=crop&q=80',
    description: 'Transforming mobile marketing, content discovery, and ad-tech with real-time AI and machine learning.',
    industry: 'AdTech & AI Platforms',
    website: 'https://inmobi.com',
    location: 'Bengaluru, India (Remote)',
    companySize: '2,500+ employees',
    foundedYear: 2007,
    socialLinks: { linkedin: 'https://linkedin.com/company/inmobi' },
    verificationStatus: 'VERIFIED',
    createdAt: '2026-01-30T10:00:00Z',
    updatedAt: '2026-01-30T10:00:00Z',
  },
  {
    id: 'comp-10',
    userId: 'user-comp-10',
    companyName: 'NovaAI Labs',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=150&auto=format&fit=crop&q=80',
    description: 'Fast-growing YC-backed generative AI startup creating intelligent voice assistants and agent workflows.',
    industry: 'Artificial Intelligence / LLM',
    website: 'https://novaaianalytics.demo',
    location: 'Remote (Worldwide)',
    companySize: '35 employees',
    foundedYear: 2024,
    socialLinks: { github: 'https://github.com/nova-ai' },
    verificationStatus: 'PENDING',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
];

export const SEED_STUDENTS: StudentProfile[] = [
  {
    id: 'student-1',
    userId: 'user-student-1',
    name: 'Rahul Sharma',
    email: 'student@internswipe.demo',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    college: 'IIT Bombay',
    degree: 'B.Tech in Computer Science and Engineering',
    year: '3rd Year (Class of 2027)',
    bio: 'Passionate full-stack developer & AI enthusiast. Built scalable microservices, won Smart India Hackathon, and love working with React, Node.js, and PyTorch.',
    skills: ['React', 'TypeScript', 'Node.js', 'Python', 'Machine Learning', 'TensorFlow', 'PostgreSQL', 'Docker', 'Tailwind CSS', 'Next.js'],
    projects: [
      {
        title: 'MedAI Diagnostics',
        description: 'Deep learning chest X-Ray anomaly detector with 94.2% accuracy and an interactive React web dashboard.',
        technologies: ['PyTorch', 'FastAPI', 'React', 'Tailwind CSS'],
        link: 'https://github.com/rahul/med-ai',
      },
      {
        title: 'CampusRide Peer Transit',
        description: 'Real-time ride-sharing PWA for university campuses with WebSockets, geospatial clustering, and Razorpay integration.',
        technologies: ['React', 'Node.js', 'Socket.IO', 'PostgreSQL', 'Redis'],
        link: 'https://github.com/rahul/campusride',
      },
    ],
    certifications: ['AWS Certified Cloud Practitioner', 'DeepLearning.AI Deep Learning Specialization'],
    resumeUrl: 'https://internswipe.demo/resumes/rahul-sharma.pdf',
    preferredDomains: ['AI/ML', 'Full-Stack Development', 'Data Science'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate (3-6 Months)',
    location: 'Mumbai / Remote',
    github: 'https://github.com/rahulsharma-dev',
    linkedin: 'https://linkedin.com/in/rahulsharma-ai',
    portfolio: 'https://rahulsharma.dev',
    gpa: '9.2 / 10.0',
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-2',
    userId: 'user-student-2',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@bits.demo',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    college: 'BITS Pilani',
    degree: 'B.E. in Electronics & Instrumentation',
    year: '4th Year',
    bio: 'Product-minded frontend architect and UI/UX developer. Obsessed with micro-interactions, smooth animation curves, and accessible design systems.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Figma', 'Framer Motion', 'Next.js', 'GraphQL', 'Storybook', 'Web Accessibility (a11y)'],
    projects: [
      {
        title: 'DesignTokens Studio',
        description: 'Open-source design token synchronization engine between Figma and Tailwind CSS variables.',
        technologies: ['TypeScript', 'Figma Plugin API', 'React'],
      },
    ],
    certifications: ['Meta Frontend Professional Certificate'],
    preferredDomains: ['UI/UX', 'Frontend Engineering', 'Product Design'],
    preferredJobType: 'REMOTE',
    availability: 'Part-Time / Full-Time Summer',
    location: 'Bengaluru / Remote',
    github: 'https://github.com/ananyaiyer',
    linkedin: 'https://linkedin.com/in/ananya-iyer-ui',
    createdAt: '2026-01-06T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-3',
    userId: 'user-student-3',
    name: 'Aarav Patel',
    email: 'aarav.patel@nit.demo',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    college: 'NIT Trichy',
    degree: 'B.Tech in Information Technology',
    year: '3rd Year',
    bio: 'Systems programmer & backend engineer who loves Go, distributed queues, and PostgreSQL query optimization.',
    skills: ['Go', 'Python', 'PostgreSQL', 'Docker', 'Kubernetes', 'Redis', 'Kafka', 'gRPC', 'Linux Systems'],
    projects: [
      {
        title: 'Distributed Rate Limiter',
        description: 'Sliding window token bucket rate limiter in Go benchmarked at 120k requests per second.',
        technologies: ['Go', 'Redis', 'gRPC'],
      },
    ],
    certifications: ['Certified Kubernetes Application Developer (CKAD)'],
    preferredDomains: ['Backend Engineering', 'Cloud & DevOps', 'Systems'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate (Summer 2026)',
    location: 'Chennai / Remote',
    github: 'https://github.com/aaravpatel-go',
    linkedin: 'https://linkedin.com/in/aaravpatel-backend',
    createdAt: '2026-01-08T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-4',
    userId: 'user-student-4',
    name: 'Pooja Reddy',
    email: 'pooja.reddy@iiit.demo',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    college: 'IIIT Hyderabad',
    degree: 'B.Tech in Computer Science',
    year: '3rd Year',
    bio: 'Natural Language Processing and LLM fine-tuning researcher. Published an ACL student workshop paper on cross-lingual embeddings.',
    skills: ['Python', 'PyTorch', 'Hugging Face', 'Transformers', 'NLP', 'LangChain', 'Vector Databases', 'SQL'],
    projects: [
      {
        title: 'IndicSumm LLM',
        description: 'Fine-tuned Gemma-2 for summarization across 7 Indian regional languages with RAG support.',
        technologies: ['PyTorch', 'Transformers', 'Qdrant', 'FastAPI'],
      },
    ],
    certifications: ['Stanford CS224N Certificate'],
    preferredDomains: ['AI/ML', 'NLP / LLMs', 'Data Science'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate (6 Months)',
    location: 'Hyderabad / Remote',
    github: 'https://github.com/poojareddy-ai',
    linkedin: 'https://linkedin.com/in/pooja-reddy-nlp',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-5',
    userId: 'user-student-5',
    name: 'Karan Malhotra',
    email: 'karan.malhotra@dtu.demo',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    college: 'Delhi Technological University (DTU)',
    degree: 'B.Tech in Software Engineering',
    year: '4th Year',
    bio: 'Mobile application developer with 3 published apps on Play Store and App Store (>50k combined downloads).',
    skills: ['Flutter', 'React Native', 'TypeScript', 'Swift', 'Firebase', 'State Management (Riverpod)', 'GraphQL'],
    projects: [
      {
        title: 'FitTrack Social',
        description: 'Social fitness logging and streak challenge app with offline-first SQLite sync and live leaderboards.',
        technologies: ['Flutter', 'Dart', 'Firebase', 'Google Fit API'],
      },
    ],
    certifications: ['Google Associate Android Developer'],
    preferredDomains: ['App Development', 'Mobile Engineering', 'Full-Stack'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate (3 Months)',
    location: 'New Delhi / Remote',
    github: 'https://github.com/karanm-mobile',
    linkedin: 'https://linkedin.com/in/karan-malhotra-dev',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-6',
    userId: 'user-student-6',
    name: 'Sneha Sengupta',
    email: 'sneha.s@vit.demo',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    college: 'VIT Vellore',
    degree: 'B.Tech in CSE (Information Security)',
    year: '3rd Year',
    bio: 'Cybersecurity analyst & bug bounty hunter. Ranked in Top 50 on Bugcrowd, skilled in penetration testing and secure code review.',
    skills: ['Cybersecurity', 'Ethical Hacking', 'Penetration Testing', 'Python', 'Wireshark', 'Burp Suite', 'Linux', 'OWASP Top 10', 'Cryptography'],
    projects: [
      {
        title: 'VulnScanner Pro',
        description: 'Automated CI/CD security scanner checking for exposed secrets, outdated dependencies, and CORS misconfigurations.',
        technologies: ['Python', 'Docker', 'GitHub Actions API'],
      },
    ],
    certifications: ['CompTIA Security+', 'eJPT Certified Junior Penetration Tester'],
    preferredDomains: ['Cybersecurity', 'Cloud Security', 'DevSecOps'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate',
    location: 'Kolkata / Remote',
    github: 'https://github.com/snehas-sec',
    linkedin: 'https://linkedin.com/in/snehasengupta-sec',
    createdAt: '2026-01-14T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-7',
    userId: 'user-student-7',
    name: 'Vikram Joshi',
    email: 'vikram.j@coep.demo',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    college: 'COEP Pune',
    degree: 'B.Tech in Computer Engineering',
    year: '2nd Year',
    bio: 'High-energy data engineer who enjoys ETL pipelines, Apache Spark, and building interactive data visualizations.',
    skills: ['Python', 'SQL', 'Apache Spark', 'Airflow', 'Tableau', 'd3.js', 'Data Warehousing', 'BigQuery'],
    projects: [
      {
        title: 'UrbanMobility Insights',
        description: 'Real-time public transit telemetry streaming pipeline ingesting 100k events/min into ClickHouse with Grafana dashboards.',
        technologies: ['Kafka', 'Apache Spark', 'Python', 'ClickHouse'],
      },
    ],
    certifications: ['Google Data Analytics Professional Certificate'],
    preferredDomains: ['Data Analytics', 'Data Engineering', 'BI & Reporting'],
    preferredJobType: 'REMOTE',
    availability: 'Flexible (3 Months)',
    location: 'Pune / Remote',
    github: 'https://github.com/vikramj-data',
    linkedin: 'https://linkedin.com/in/vikram-joshi-data',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-8',
    userId: 'user-student-8',
    name: 'Diya Nambiar',
    email: 'diya.nambiar@manipal.demo',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    college: 'Manipal Institute of Technology',
    degree: 'B.Tech in Computer Science',
    year: '4th Year',
    bio: 'Product Designer & Frontend Engineer creating human-centric consumer interfaces. Won 3 national hackathons.',
    skills: ['UI/UX', 'Figma', 'User Research', 'React', 'Tailwind CSS', 'Prototyping', 'Design Systems', 'HTML/CSS'],
    projects: [
      {
        title: 'Kavach Disaster Alert UI',
        description: 'Award-winning accessible emergency broadcast interface tested with elderly and low-literacy users.',
        technologies: ['Figma', 'React', 'Tailwind CSS'],
      },
    ],
    certifications: ['Google UX Design Professional Certificate'],
    preferredDomains: ['UI/UX', 'Product Design', 'Frontend'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate (Full-Time Intern)',
    location: 'Kochi / Remote',
    github: 'https://github.com/diyanambiar-design',
    linkedin: 'https://linkedin.com/in/diya-nambiar-ux',
    portfolio: 'https://diyanambiar.design',
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-9',
    userId: 'user-student-9',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@bms.demo',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
    college: 'BMS College of Engineering, Bengaluru',
    degree: 'B.E. in Information Science',
    year: '3rd Year',
    bio: 'Cloud architect in the making. Enthusiastic about Terraform, AWS lambda serverless architecture, and CI/CD pipelines.',
    skills: ['AWS', 'Docker', 'Terraform', 'CI/CD', 'Node.js', 'Linux', 'Python', 'Bash', 'GitHub Actions'],
    projects: [
      {
        title: 'Serverless Video Transcoder',
        description: 'Event-driven video compression pipeline on AWS Lambda and SQS that reduces bandwidth costs by 65%.',
        technologies: ['AWS Lambda', 'FFmpeg', 'Node.js', 'Terraform'],
      },
    ],
    certifications: ['AWS Solutions Architect Associate'],
    preferredDomains: ['Cloud Computing', 'DevOps', 'Backend'],
    preferredJobType: 'REMOTE',
    availability: 'Summer 2026',
    location: 'Bengaluru / Remote',
    github: 'https://github.com/rohand-cloud',
    linkedin: 'https://linkedin.com/in/rohan-deshmukh-cloud',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'student-10',
    userId: 'user-student-10',
    name: 'Meera Chawla',
    email: 'meera.c@nsut.demo',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    college: 'Netaji Subhas University of Technology (NSUT)',
    degree: 'B.Tech in Artificial Intelligence',
    year: '3rd Year',
    bio: 'Computer Vision explorer working on 3D reconstruction and generative adversarial networks. Open-source contributor to OpenCV.',
    skills: ['Python', 'OpenCV', 'PyTorch', 'Computer Vision', 'Deep Learning', 'C++', 'NumPy', 'TensorFlow'],
    projects: [
      {
        title: 'GestureNav Interface',
        description: 'Real-time hand gesture recognition controlling browser and presentation navigation via standard webcam.',
        technologies: ['Python', 'MediaPipe', 'OpenCV', 'PyTorch'],
      },
    ],
    certifications: ['DeepLearning.AI Computer Vision Specialization'],
    preferredDomains: ['AI/ML', 'Computer Vision', 'Data Science'],
    preferredJobType: 'REMOTE',
    availability: 'Immediate (6 Months)',
    location: 'Delhi / Remote',
    github: 'https://github.com/meerac-vision',
    linkedin: 'https://linkedin.com/in/meera-chawla-ai',
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
];

export const SEED_INTERNSHIPS: Internship[] = [
  {
    id: 'intern-1',
    companyId: 'comp-1',
    companyName: 'Google India',
    companyLogo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Machine Learning Research Intern',
    description: 'Collaborate with Google AI research teams to develop novel transformer architectures, optimize large model inferences, and deploy multimodal solutions at planetary scale.',
    category: 'AI/ML',
    requiredSkills: ['Python', 'Machine Learning', 'TensorFlow', 'PyTorch', 'SQL'],
    preferredSkills: ['Deep Learning', 'C++', 'Distributed Computing', 'Transformers'],
    stipend: 35000,
    currency: '₹',
    duration: '3 - 6 Months',
    workType: 'REMOTE',
    location: 'Remote / Bengaluru Hub',
    workingHours: 'Flexible (40 hrs/wk)',
    experienceLevel: 'Intermediate',
    deadline: '2026-09-30',
    status: 'ACTIVE',
    openings: 5,
    perks: ['Mentorship from Google Staff Scientists', 'Hardware Stipend', 'PPO Opportunity', 'Free Learning Resources'],
    responsibilities: [
      'Design, train, and benchmark deep learning models for NLP and computer vision tasks',
      'Analyze massive datasets and conduct experimental ablation studies',
      'Collaborate with product and infrastructure engineers on production inference pipelines',
    ],
    requirements: [
      'Strong proficiency in Python and modern ML frameworks (PyTorch or TensorFlow)',
      'Understanding of linear algebra, probability, and neural network fundamentals',
      'Prior projects or research experience in ML/AI',
    ],
    likesCount: 142,
    applicantsCount: 48,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'intern-2',
    companyId: 'comp-2',
    companyName: 'Swiggy',
    companyLogo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Full-Stack Engineering Intern (React & Node)',
    description: 'Build mission-critical user facing experiences and high-concurrency microservices powering millions of daily food and grocery deliveries across 500+ Indian cities.',
    category: 'Web Development',
    requiredSkills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    preferredSkills: ['Next.js', 'Redis', 'Docker', 'RESTful APIs'],
    stipend: 25000,
    currency: '₹',
    duration: '3 Months',
    workType: 'REMOTE',
    location: 'Bengaluru / Remote',
    workingHours: 'Full-time (40 hrs/wk)',
    experienceLevel: 'Beginner to Intermediate',
    deadline: '2026-09-15',
    status: 'ACTIVE',
    openings: 8,
    perks: ['Swiggy One VIP Subscription', 'Fast-track PPO Consideration', 'Work From Anywhere Allowance'],
    responsibilities: [
      'Implement performant responsive React web components with sub-100ms interaction latency',
      'Develop robust REST and GraphQL API routes in Node.js/TypeScript',
      'Write comprehensive unit and integration test suites',
    ],
    requirements: [
      'Hands-on experience with modern React, JavaScript/TypeScript, and state management',
      'Familiarity with relational databases (PostgreSQL or MySQL)',
      'Demonstrated portfolio projects demonstrating clean UI and solid backend integration',
    ],
    likesCount: 98,
    applicantsCount: 32,
    createdAt: '2026-02-02T10:00:00Z',
    updatedAt: '2026-02-02T10:00:00Z',
  },
  {
    id: 'intern-3',
    companyId: 'comp-3',
    companyName: 'Razorpay',
    companyLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Backend Platform Intern (Go / Distributed Systems)',
    description: 'Work on payment routing gateways, bank reconciliation engines, and idempotency pipelines handling billions of dollars in transaction volume with 99.999% uptime.',
    category: 'Backend Engineering',
    requiredSkills: ['Go', 'PostgreSQL', 'Docker', 'Redis', 'Linux'],
    preferredSkills: ['Kafka', 'Microservices', 'gRPC', 'Distributed Systems'],
    stipend: 30000,
    currency: '₹',
    duration: '6 Months',
    workType: 'REMOTE',
    location: 'Remote (India)',
    workingHours: 'Full-time',
    experienceLevel: 'Intermediate',
    deadline: '2026-09-25',
    status: 'ACTIVE',
    openings: 4,
    perks: ['Competitive Stipend', 'Health Insurance for Intern', 'Home Office Setup Reimbursement'],
    responsibilities: [
      'Develop microservices in Golang with ultra-low latency requirements',
      'Optimize database queries and implement distributed caching patterns with Redis',
      'Instrument telemetry, alerting, and observability with Prometheus & Grafana',
    ],
    requirements: [
      'Proficiency in Golang or strong backend fundamentals in Java/C++/Python with Go willingness',
      'Understanding of ACID transactions, concurrency, and RESTful architectures',
    ],
    likesCount: 88,
    applicantsCount: 26,
    createdAt: '2026-02-03T10:00:00Z',
    updatedAt: '2026-02-03T10:00:00Z',
  },
  {
    id: 'intern-4',
    companyId: 'comp-4',
    companyName: 'CRED',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Product UI/UX & Frontend Intern',
    description: 'Craft the legendary CRED visual aesthetic. Build physics-based fluid web experiences, 3D Canvas visualizers, and pixel-perfect design systems that set industry standards.',
    category: 'UI/UX',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'Figma', 'Framer Motion'],
    preferredSkills: ['Three.js', 'Canvas API', 'Design Systems', 'CSS Shaders'],
    stipend: 25000,
    currency: '₹',
    duration: '3 - 6 Months',
    workType: 'HYBRID',
    location: 'Bengaluru (Hybrid / Remote Flex)',
    workingHours: 'Full-time',
    experienceLevel: 'All levels',
    deadline: '2026-09-20',
    status: 'ACTIVE',
    openings: 3,
    perks: ['Gourmet Office Meals (when on-site)', 'CRED Club Gear', 'High-impact product ownership'],
    responsibilities: [
      'Translate experimental visual designs from Figma into ultra-smooth 60fps web apps',
      'Build reusable design system tokens and headless interactive primitives',
      'Conduct accessibility and rendering performance audits',
    ],
    requirements: [
      'Exceptional eye for typography, spacing, motion physics, and color balance',
      'Strong knowledge of React, Tailwind CSS, and Framer Motion',
    ],
    likesCount: 165,
    applicantsCount: 54,
    createdAt: '2026-02-04T10:00:00Z',
    updatedAt: '2026-02-04T10:00:00Z',
  },
  {
    id: 'intern-5',
    companyId: 'comp-5',
    companyName: 'Zerodha Tech',
    companyLogo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Data Science & Market Analytics Intern',
    description: 'Work alongside the quantitative analytics team analyzing market order flow, user behavioral patterns, and building automated reporting infrastructure using open-source tools.',
    category: 'Data Science',
    requiredSkills: ['Python', 'SQL', 'Data Analytics', 'Pandas', 'NumPy'],
    preferredSkills: ['PostgreSQL', 'Matplotlib', 'Statistics', 'Financial Markets'],
    stipend: 20000,
    currency: '₹',
    duration: '3 Months',
    workType: 'REMOTE',
    location: 'Remote-First (Anywhere)',
    workingHours: 'Flexible',
    experienceLevel: 'Intermediate',
    deadline: '2026-10-15',
    status: 'ACTIVE',
    openings: 3,
    perks: ['True Remote Culture', 'Zero Micromanagement', 'Open Source Contribution Encouraged'],
    responsibilities: [
      'Clean and process high-frequency financial time-series data',
      'Construct statistical models to evaluate trading engagement metrics',
      'Build automated exploratory dashboards and visualizations',
    ],
    requirements: [
      'Strong foundations in Python, Pandas, SQL, and applied probability',
      'Curiosity for capital markets, fintech, and data ethics',
    ],
    likesCount: 110,
    applicantsCount: 38,
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'intern-6',
    companyId: 'comp-6',
    companyName: 'Postman',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Developer Experience & Cloud Intern',
    description: 'Shape the future of API collaboration. Build CLI extensions, test runner integrations, and developer documentation features used by millions of engineers daily.',
    category: 'Cloud Computing',
    requiredSkills: ['TypeScript', 'Node.js', 'Docker', 'AWS', 'CI/CD'],
    preferredSkills: ['GraphQL', 'Electron', 'RESTful APIs', 'OpenAPI Specs'],
    stipend: 28000,
    currency: '₹',
    duration: '4 Months',
    workType: 'REMOTE',
    location: 'Remote (India)',
    workingHours: 'Flexible',
    experienceLevel: 'Intermediate',
    deadline: '2026-10-01',
    status: 'ACTIVE',
    openings: 5,
    perks: ['Postman Developer Certification Voucher', 'PPO Track', 'Annual Home Office Grant'],
    responsibilities: [
      'Enhance API mocking, testing, and monitoring capabilities',
      'Improve developer onboarding flows and automated CLI tooling',
      'Write technical tutorials and sample workspace collections',
    ],
    requirements: [
      'Deep appreciation for API design (REST/GraphQL/gRPC)',
      'Experience in TypeScript, Node.js, and containerized workflows',
    ],
    likesCount: 76,
    applicantsCount: 22,
    createdAt: '2026-02-06T10:00:00Z',
    updatedAt: '2026-02-06T10:00:00Z',
  },
  {
    id: 'intern-7',
    companyId: 'comp-7',
    companyName: 'Atlassian',
    companyLogo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Cloud Security & DevSecOps Intern',
    description: 'Protect enterprise data across Jira, Confluence, and Bitbucket. Implement automated vulnerability scanning, OAuth validation, and security monitoring guardrails.',
    category: 'Cybersecurity',
    requiredSkills: ['Cybersecurity', 'Python', 'Linux', 'AWS', 'OWASP Top 10'],
    preferredSkills: ['Terraform', 'Ethical Hacking', 'Docker', 'SIEM Tools'],
    stipend: 32000,
    currency: '₹',
    duration: '6 Months',
    workType: 'REMOTE',
    location: 'Remote (India)',
    workingHours: 'Full-time',
    experienceLevel: 'Intermediate',
    deadline: '2026-10-10',
    status: 'ACTIVE',
    openings: 3,
    perks: ['Atlassian Team Playbook Training', 'Generous Wellness Allowance', 'Direct PPO Route'],
    responsibilities: [
      'Conduct automated vulnerability assessments on cloud deployments',
      'Assist with incident triage and security bug reproduction',
      'Implement secure code linting rules into CI/CD pipelines',
    ],
    requirements: [
      'Understanding of web security vulnerabilities (XSS, CSRF, SSRF, SQLi)',
      'Familiarity with AWS IAM, container security, and secure coding practices',
    ],
    likesCount: 92,
    applicantsCount: 29,
    createdAt: '2026-02-07T10:00:00Z',
    updatedAt: '2026-02-07T10:00:00Z',
  },
  {
    id: 'intern-8',
    companyId: 'comp-8',
    companyName: 'Flipkart',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Mobile App Engineer Intern (React Native / Flutter)',
    description: 'Work on high-volume consumer commerce apps during the Big Billion Days shopping festivals. Focus on offline resilience, checkout speed, and battery efficiency.',
    category: 'App Development',
    requiredSkills: ['React Native', 'Flutter', 'TypeScript', 'Mobile Engineering', 'RESTful APIs'],
    preferredSkills: ['Redux', 'Native Android (Kotlin)', 'iOS (Swift)', 'Firebase'],
    stipend: 22000,
    currency: '₹',
    duration: '3 - 6 Months',
    workType: 'HYBRID',
    location: 'Bengaluru (Hybrid)',
    workingHours: 'Full-time',
    experienceLevel: 'Beginner to Intermediate',
    deadline: '2026-09-28',
    status: 'ACTIVE',
    openings: 6,
    perks: ['Flipkart Plus Premium Membership', 'Mentorship from Principal Engineers', 'Campus to Flipkart PPO Option'],
    responsibilities: [
      'Build engaging mobile UI components with smooth 60fps scrolling',
      'Integrate push notification services and deep linking schemes',
      'Optimize network payloads and offline local storage caching',
    ],
    requirements: [
      'Experience with React Native or Flutter framework',
      'Solid grasp of mobile UX patterns, state management, and async networking',
    ],
    likesCount: 115,
    applicantsCount: 41,
    createdAt: '2026-02-08T10:00:00Z',
    updatedAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'intern-9',
    companyId: 'comp-9',
    companyName: 'InMobi',
    companyLogo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Generative AI & LLM Systems Intern',
    description: 'Build autonomous agent workflows, prompt chaining pipelines, and RAG architectures that automatically generate engaging contextual multimedia ad copy.',
    category: 'AI/ML',
    requiredSkills: ['Python', 'Machine Learning', 'NLP', 'LangChain', 'SQL'],
    preferredSkills: ['Vector Databases', 'Hugging Face', 'FastAPI', 'Docker'],
    stipend: 25000,
    currency: '₹',
    duration: '3 Months',
    workType: 'REMOTE',
    location: 'Remote',
    workingHours: 'Flexible',
    experienceLevel: 'Intermediate',
    deadline: '2026-10-05',
    status: 'ACTIVE',
    openings: 4,
    perks: ['AI Hackathon Access', 'Cloud GPU Compute Credits', 'Certificate & Recommendation Letter'],
    responsibilities: [
      'Implement Retrieval Augmented Generation (RAG) over marketing knowledge graphs',
      'Evaluate model hallucination rates and latency trade-offs',
      'Integrate LLM endpoints with backend application layers',
    ],
    requirements: [
      'Familiarity with generative AI SDKs, embeddings, vector search, and prompting patterns',
      'Strong Python and data handling capabilities',
    ],
    likesCount: 130,
    applicantsCount: 45,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },
  {
    id: 'intern-10',
    companyId: 'comp-10',
    companyName: 'NovaAI Labs',
    companyLogo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=150&auto=format&fit=crop&q=80',
    companyVerified: false,
    title: 'Full-Stack AI Product Intern (FastAPI & Next.js)',
    description: 'Join a fast-moving YC startup as an early intern. Ship real features every week, prototype voice interfaces, and interact directly with early enterprise adopters.',
    category: 'Software Engineering',
    requiredSkills: ['React', 'Next.js', 'Python', 'TypeScript', 'Tailwind CSS'],
    preferredSkills: ['FastAPI', 'WebSockets', 'AI Agents', 'Supabase'],
    stipend: 18000,
    currency: '₹',
    duration: '3 Months',
    workType: 'REMOTE',
    location: 'Remote (Worldwide)',
    workingHours: 'Flexible (Startup Speed)',
    experienceLevel: 'Beginner to Intermediate',
    deadline: '2026-10-20',
    status: 'ACTIVE',
    openings: 2,
    perks: ['Startup Equity Upside Potential', 'Direct Mentorship from YC Alumni Founders', 'Flexible Hours'],
    responsibilities: [
      'Build end-to-end full stack features across Next.js frontend and Python FastAPI services',
      'Implement real-time WebSockets for low-latency voice streaming',
      'Talk with users and iterate rapidly on UX feedback',
    ],
    requirements: [
      'Enthusiastic self-starter who loves building things from scratch',
      'Proficiency in React/TypeScript and Python',
    ],
    likesCount: 65,
    applicantsCount: 19,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'intern-11',
    companyId: 'comp-1',
    companyName: 'Google India',
    companyLogo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Software Engineering Intern - Web Performance & Core Vitals',
    description: 'Collaborate with the Chrome and Search web platform engineering teams to diagnose, benchmark, and optimize modern browser rendering engines and WebAssembly execution.',
    category: 'Software Engineering',
    requiredSkills: ['JavaScript', 'TypeScript', 'C++', 'Algorithms', 'Web Performance'],
    preferredSkills: ['WebAssembly', 'Chromium Internals', 'Rust'],
    stipend: 35000,
    currency: '₹',
    duration: '3 - 6 Months',
    workType: 'REMOTE',
    location: 'Remote / Hyderabad Hub',
    workingHours: 'Full-time',
    experienceLevel: 'Intermediate',
    deadline: '2026-10-30',
    status: 'ACTIVE',
    openings: 4,
    perks: ['Full Google Intern Stipend', 'Mentorship from Staff Engineers', 'PPO Track'],
    responsibilities: ['Benchmark browser rendering pipelines', 'Write memory profiling tools in TypeScript & C++'],
    requirements: ['Solid CS fundamentals (Data Structures, OS, Memory Management)', 'Strong coding skills in C++ or TypeScript'],
    likesCount: 104,
    applicantsCount: 39,
    createdAt: '2026-02-11T10:00:00Z',
    updatedAt: '2026-02-11T10:00:00Z',
  },
  {
    id: 'intern-12',
    companyId: 'comp-3',
    companyName: 'Razorpay',
    companyLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150&auto=format&fit=crop&q=80',
    companyVerified: true,
    title: 'Frontend Platform & Checkout Experience Intern',
    description: 'Help architect the next generation of Razorpay Standard Checkout SDK used by over 8 million Indian merchants to process credit cards, UPI, and netbanking securely.',
    category: 'Web Development',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'JavaScript', 'HTML/CSS'],
    preferredSkills: ['Micro-frontends', 'Webpack/Vite plugins', 'Accessibility (WCAG)'],
    stipend: 25000,
    currency: '₹',
    duration: '3 Months',
    workType: 'REMOTE',
    location: 'Remote (India)',
    workingHours: 'Full-time',
    experienceLevel: 'Beginner to Intermediate',
    deadline: '2026-10-15',
    status: 'ACTIVE',
    openings: 4,
    perks: ['Competitive Stipend', 'Mentorship', 'PPO Opportunity'],
    responsibilities: ['Optimize bundle sizes and sub-50ms JS bootstrap times', 'Build cross-browser payment modal components'],
    requirements: ['Strong vanilla JS and React fundamentals', 'Passion for web performance'],
    likesCount: 84,
    applicantsCount: 28,
    createdAt: '2026-02-12T10:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  }
];

export const SEED_SWIPES: Swipe[] = [
  {
    id: 'swipe-1',
    studentId: 'student-1',
    internshipId: 'intern-1',
    companyId: 'comp-1',
    action: 'LIKE',
    actorRole: 'STUDENT',
    createdAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'swipe-2',
    studentId: 'student-1',
    internshipId: 'intern-2',
    companyId: 'comp-2',
    action: 'LIKE',
    actorRole: 'STUDENT',
    createdAt: '2026-02-06T10:30:00Z',
  },
  {
    id: 'swipe-3',
    studentId: 'student-1',
    internshipId: 'intern-3',
    companyId: 'comp-3',
    action: 'PASS',
    actorRole: 'STUDENT',
    createdAt: '2026-02-06T11:00:00Z',
  },
  // Recruiter swipe on student-1 creating mutual match
  {
    id: 'swipe-comp-1',
    studentId: 'student-1',
    internshipId: 'intern-1',
    companyId: 'comp-1',
    action: 'LIKE',
    actorRole: 'COMPANY',
    createdAt: '2026-02-05T15:00:00Z',
  },
  {
    id: 'swipe-comp-2',
    studentId: 'student-1',
    internshipId: 'intern-2',
    companyId: 'comp-2',
    action: 'LIKE',
    actorRole: 'COMPANY',
    createdAt: '2026-02-06T12:00:00Z',
  }
];

export const SEED_MATCHES: Match[] = [
  {
    id: 'match-1',
    studentId: 'student-1',
    student: SEED_STUDENTS[0],
    companyId: 'comp-1',
    company: SEED_COMPANIES[0],
    internshipId: 'intern-1',
    internship: SEED_INTERNSHIPS[0],
    createdAt: '2026-02-05T15:00:00Z',
    status: 'ACTIVE',
    lastMessage: 'Hi Rahul! We were super impressed with your MedAI project. Would love to schedule a quick 20-min technical sync!',
    lastMessageAt: '2026-02-06T16:30:00Z',
    unreadCountStudent: 1,
    unreadCountCompany: 0,
  },
  {
    id: 'match-2',
    studentId: 'student-1',
    student: SEED_STUDENTS[0],
    companyId: 'comp-2',
    company: SEED_COMPANIES[1],
    internshipId: 'intern-2',
    internship: SEED_INTERNSHIPS[1],
    createdAt: '2026-02-06T12:00:00Z',
    status: 'ACTIVE',
    lastMessage: 'Hey Rahul, thanks for connecting on InternSwipe! Your React + Node profile looks very solid for our consumer team.',
    lastMessageAt: '2026-02-07T09:15:00Z',
    unreadCountStudent: 0,
    unreadCountCompany: 0,
  }
];

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    studentId: 'student-1',
    student: SEED_STUDENTS[0],
    internshipId: 'intern-1',
    internship: SEED_INTERNSHIPS[0],
    companyId: 'comp-1',
    company: SEED_COMPANIES[0],
    status: 'INTERVIEW',
    coverLetter: 'I am thrilled to apply for the Machine Learning Research Intern role at Google India. With my background in deep learning, transformer models, and scalable full-stack applications, I am eager to contribute to cutting-edge research.',
    resumeUrl: 'https://internswipe.demo/resumes/rahul-sharma.pdf',
    timeline: [
      { status: 'APPLIED', date: '2026-02-05 15:30', note: 'Applied following mutual match on InternSwipe' },
      { status: 'UNDER_REVIEW', date: '2026-02-06 09:00', note: 'Profile and code samples reviewed by AI Research Lead' },
      { status: 'SHORTLISTED', date: '2026-02-06 14:00', note: 'Selected for technical evaluation round' },
      { status: 'INTERVIEW', date: '2026-02-07 10:00', note: 'Technical Interview scheduled for Feb 16, 2026 at 2:00 PM IST' },
    ],
    notes: 'Candidate demonstrated outstanding depth in deep learning architectures and clean coding practices during initial screening.',
    createdAt: '2026-02-05T15:30:00Z',
    updatedAt: '2026-02-07T10:00:00Z',
  },
  {
    id: 'app-2',
    studentId: 'student-1',
    student: SEED_STUDENTS[0],
    internshipId: 'intern-2',
    internship: SEED_INTERNSHIPS[1],
    companyId: 'comp-2',
    company: SEED_COMPANIES[1],
    status: 'SHORTLISTED',
    coverLetter: 'Excited about the full-stack engineering opportunity at Swiggy. I have built real-time WebSockets transit apps and look forward to building high-concurrency food delivery systems.',
    resumeUrl: 'https://internswipe.demo/resumes/rahul-sharma.pdf',
    timeline: [
      { status: 'APPLIED', date: '2026-02-06 12:30', note: 'Application submitted through 1-click Match Apply' },
      { status: 'UNDER_REVIEW', date: '2026-02-06 16:00', note: 'Assigned to Swiggy Engineering Team Lead' },
      { status: 'SHORTLISTED', date: '2026-02-07 11:30', note: 'Candidate shortlisted for coding challenge' },
    ],
    createdAt: '2026-02-06T12:30:00Z',
    updatedAt: '2026-02-07T11:30:00Z',
  }
];

export const SEED_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    matchId: 'match-1',
    senderId: 'user-comp-1',
    senderRole: 'COMPANY',
    senderName: 'Dr. Priya N (Google AI Recruiter)',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    content: 'Hi Rahul! We came across your profile and were super impressed with your MedAI chest x-ray detector and deep learning background.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2026-02-06T16:20:00Z',
  },
  {
    id: 'msg-2',
    matchId: 'match-1',
    senderId: 'user-comp-1',
    senderRole: 'COMPANY',
    senderName: 'Dr. Priya N (Google AI Recruiter)',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    content: 'We have an opening on our Transformer Inference Optimization team. Are you available for a 20-min technical sync this week?',
    type: 'TEXT',
    isRead: false,
    createdAt: '2026-02-06T16:30:00Z',
  },
  {
    id: 'msg-3',
    matchId: 'match-2',
    senderId: 'user-comp-2',
    senderRole: 'COMPANY',
    senderName: 'Arjun Verma (Swiggy Tech Talent)',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    content: 'Hey Rahul, thanks for connecting on InternSwipe! Your React + Node profile looks very solid for our consumer team.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2026-02-07T09:15:00Z',
  },
  {
    id: 'msg-4',
    matchId: 'match-2',
    senderId: 'user-student-1',
    senderRole: 'STUDENT',
    senderName: 'Rahul Sharma',
    senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80',
    content: 'Thank you Arjun! Really excited about Swiggy’s delivery scale. I have shared my full resume and GitHub repositories in my application.',
    type: 'TEXT',
    isRead: true,
    createdAt: '2026-02-07T09:30:00Z',
  }
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-student-1',
    title: 'It’s a Match! 🎉',
    message: 'You and Google India liked each other for the Machine Learning Research Intern position.',
    type: 'MATCH',
    link: '/messages',
    isRead: false,
    createdAt: '2026-02-05T15:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-student-1',
    title: 'New Message from Recruiter',
    message: 'Dr. Priya N from Google India sent you a message.',
    type: 'MESSAGE',
    link: '/messages',
    isRead: false,
    createdAt: '2026-02-06T16:30:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-student-1',
    title: 'Application Status Updated',
    message: 'Your Google India application is now in the INTERVIEW stage!',
    type: 'APPLICATION',
    link: '/student/applications',
    isRead: false,
    createdAt: '2026-02-07T10:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-student-1',
    title: 'AI Top Recommendation',
    message: 'New 94% match: Full-Stack Engineering Intern at Swiggy matches your React & Node.js skills.',
    type: 'AI_RECOMMENDATION',
    link: '/student/swipe',
    isRead: true,
    createdAt: '2026-02-04T09:00:00Z',
  }
];

export const SEED_REPORTS: ReportItem[] = [
  {
    id: 'report-1',
    reporterId: 'user-student-3',
    reporterName: 'Aarav Patel',
    targetType: 'COMPANY',
    targetId: 'comp-10',
    targetName: 'NovaAI Labs',
    reason: 'Suspicious company information',
    details: 'The company website returned a 404 page when clicked during discovery.',
    status: 'PENDING',
    createdAt: '2026-02-08T12:00:00Z',
  }
];
